### ISSUE TITLE
Importing ToastVariant causes @ns to be lost

### ISSUE THREAD

**Issue by fluxxdog** [Tanimodori/viteburner#22] opened 2023-12-29 12:06 UTC
Kept getting error messages like this:

`6:57:34 AM [viteburner] Error: Failed to resolve import "@ns" from "src\support\FarmServer.ts". Does the file exist?`

I included the working file as an upload. On line 30, I just used the value to get it working. If I swap it out for the ToastVariant enum and import ToastVariant, I'll get error messages and the file won't upload.

[toasty.txt](https://github.com/Tanimodori/viteburner/files/13793281/toasty.txt)

**Comment by Tanimodori** [comment] 2024-01-02 02:44
duplicate of #17

**Closed as not planned by Tanimodori** 2024-01-02 02:44 UTC
